START TRANSACTION;

ALTER TABLE search_engine_results2
ADD COLUMN SCRAPED_WEBSITE TEXT;

UPDATE search_engine_results2
SET SCRAPED_WEBSITE = CASE
                        WHEN WEBSITE = SCRAPED_WEBSITE_1 THEN SCRAPED_WEBSITE_1
                        WHEN WEBSITE = SCRAPED_WEBSITE_2 THEN SCRAPED_WEBSITE_2
                        WHEN WEBSITE = SCRAPED_WEBSITE_3 THEN SCRAPED_WEBSITE_3
                        ELSE SCRAPED_WEBSITE_1


ALTER TABLE search_engine_results
ADD COLUMN SCRAPED_WEBSITE TEXT;

UPDATE search_engine_results
SET SCRAPED_WEBSITE = SCRAPED_WEBSITE_1
COMMIT;